# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_carrito_detall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nom',
        ),
    ]
